steps:
- name: gcr.io/cloud-builders/gsutil
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    curl --trace-ascii -  -H"cookie: $(gsutil cat gs://bmenasha-spinnaker-demo-1-utilities/sessioncookie.txt)" -XPOST   --data-ascii @spinnaker-pipeline.json -H'content-type: application/json' -k https://spinnaker-api.gcpidentityexample-2.com/pipelines
