steps:
- name: gcr.io/cloud-builders/gsutil
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    gsutil cp  gs://bmenasha-spinnaker-demo-1-utilities/spin .
    mkdir /builder/home/.spin
    gsutil cp gs://bmenasha-spinnaker-demo-1-utilities/spin-config /builder/home/.spin/config
    chmod +x spin
    ls
    echo `ls`
    ./spin pipeline save --file spinnaker-pipeline.json --gate-endpoint https://spinnaker-api.gcpidentityexample-2.com  --insecure
